<a href="https://colab.research.google.com/github/nicoRomeroCuruchet/FlightController/blob/main/quaternions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: Print in latex and use phi theta and psi
from sympy.physics.mechanics import ReferenceFrame
from sympy import simplify, trigsimp,symbols, cos, sin, Matrix, pi, Quaternion

phi, theta, psi, phi_dot, theta_dot, psi_dot = symbols('phi theta psi phi_dot theta_dot psi_dot')

# The rotation matrices to transform vector from world frame to body frame:
Rx = Matrix([[1, 0,        0       ],
            [0,  cos(phi), sin(phi)],
            [0,  -sin(phi), cos(phi)]])

Ry = Matrix([[cos(theta),  0, -sin(theta) ],
             [0,           1, 0          ],
             [sin(theta), 0,  cos(theta)]])

Rz = Matrix([[cos(psi),  sin(psi), 0],
             [-sin(psi), cos(psi), 0],
             [0,         0,        1]])

Rotation_matrix = Rx * Ry * Rz
from sympy.printing.latex import LatexPrinter
lp = LatexPrinter()
print("$"+lp.doprint(Rotation_matrix)+"$")

Transform vector from the frame of the world to the frame of the body:

$T^{b}_{w} = \left[\begin{matrix}\cos{\left(\psi \right)} \cos{\left(\theta \right)} & \sin{\left(\psi \right)} \cos{\left(\theta \right)} & - \sin{\left(\theta \right)}\\\sin{\left(\phi \right)} \sin{\left(\theta \right)} \cos{\left(\psi \right)} - \sin{\left(\psi \right)} \cos{\left(\phi \right)} & \sin{\left(\phi \right)} \sin{\left(\psi \right)} \sin{\left(\theta \right)} + \cos{\left(\phi \right)} \cos{\left(\psi \right)} & \sin{\left(\phi \right)} \cos{\left(\theta \right)}\\\sin{\left(\phi \right)} \sin{\left(\psi \right)} + \sin{\left(\theta \right)} \cos{\left(\phi \right)} \cos{\left(\psi \right)} & - \sin{\left(\phi \right)} \cos{\left(\psi \right)} + \sin{\left(\psi \right)} \sin{\left(\theta \right)} \cos{\left(\phi \right)} & \cos{\left(\phi \right)} \cos{\left(\theta \right)}\end{matrix}\right]$


In [ ]:
print("$"+lp.doprint(Rotation_matrix.T)+"$")

Transform vector from the body frame to the frame of the world:

$T^{w}_{b} = \left[\begin{matrix}\cos{\left(\psi \right)} \cos{\left(\theta \right)} & \sin{\left(\phi \right)} \sin{\left(\theta \right)} \cos{\left(\psi \right)} - \sin{\left(\psi \right)} \cos{\left(\phi \right)} & \sin{\left(\phi \right)} \sin{\left(\psi \right)} + \sin{\left(\theta \right)} \cos{\left(\phi \right)} \cos{\left(\psi \right)}\\\sin{\left(\psi \right)} \cos{\left(\theta \right)} & \sin{\left(\phi \right)} \sin{\left(\psi \right)} \sin{\left(\theta \right)} + \cos{\left(\phi \right)} \cos{\left(\psi \right)} & - \sin{\left(\phi \right)} \cos{\left(\psi \right)} + \sin{\left(\psi \right)} \sin{\left(\theta \right)} \cos{\left(\phi \right)}\\- \sin{\left(\theta \right)} & \sin{\left(\phi \right)} \cos{\left(\theta \right)} & \cos{\left(\phi \right)} \cos{\left(\theta \right)}\end{matrix}\right]$


In [ ]:
# Define the symbols
q0, q1, q2, q3 = symbols('q0 q1 q2 q3')

# Define the quaternion
q_x = Quaternion(cos(phi/2), sin(phi/2), 0, 0)
q_y = Quaternion(cos(theta/2), 0, sin(theta/2), 0)
q_z = Quaternion(cos(psi/2), 0, 0, sin(psi/2))

# Define the rotation matrix
Q = q_z * q_y * q_x
Q_conj = Q.conjugate()

In [ ]:
qw = Q.a
qx = Q.b
qy = Q.c
qz = Q.d

In [ ]:
# Roll angle (phi)
simplify((qw * qx +  qy * qz) /  (0.5 - (qx * qx + qy * qy)))

1.0*tan(phi)

In [ ]:
# Pitch angle (theta)
simplify(2  * (qw * qy - qz * qx ))

sin(theta)

In [ ]:
# Yaw angle (psi)
simplify((qw * qz +  qx * qy) /  (0.5 - (qy * qy + qz * qz)))

1.0*tan(psi)

In [ ]:
# https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles

R11 = simplify(trigsimp(1 - 2*qy**2 - 2*qz**2))
R12 = simplify(trigsimp(2*qx*qy - 2*qz*qw))
R13 = simplify(trigsimp(2*qx*qz + 2*qy*qw))

R21 = simplify(trigsimp(2*qx*qy + 2*qz*qw))
R22 = simplify(trigsimp(1 - 2*qx**2 - 2*qz**2))
R23 = simplify(trigsimp(2*qy*qz - 2*qx*qw))

R31 = simplify(trigsimp(2*qx*qz - 2*qy*qw))
R32 = simplify(trigsimp(2*qy*qz + 2*qx*qw))
R33 = simplify(trigsimp(1 - 2*qx**2 - 2*qy**2))

Matrix([[R11, R12, R13], [R21, R22, R23], [R31, R32, R33]])

Matrix([
[cos(psi)*cos(theta), sin(phi)*sin(theta)*cos(psi) - sin(psi)*cos(phi),  sin(phi)*sin(psi) + sin(theta)*cos(phi)*cos(psi)],
[sin(psi)*cos(theta), sin(phi)*sin(psi)*sin(theta) + cos(phi)*cos(psi), -sin(phi)*cos(psi) + sin(psi)*sin(theta)*cos(phi)],
[        -sin(theta),                              sin(phi)*cos(theta),                               cos(phi)*cos(theta)]])

Matrix([
[                      phi_dot - psi_dot*sin(theta)],
[psi_dot*sin(phi)*cos(theta) + theta_dot*cos(theta)],
[  psi_dot*cos(phi)*cos(theta) - theta_dot*sin(phi)]])

In [ ]:
Wx, Wy, Wz = symbols('Wx Wy Wz')
v = Quaternion(0, 0, 0, Wz)
res_quat = Q * v * Q_conj

In [ ]:
simplify(trigsimp(res_quat.b))

Wz*(sin(phi)*sin(psi) + sin(theta)*cos(phi)*cos(psi))

In [ ]:
simplify(trigsimp(res_quat.c))

Wx*sin(psi)*cos(theta) + Wy*sin(phi)*sin(psi)*sin(theta) + Wy*cos(phi)*cos(psi) - Wz*sin(phi)*cos(psi) + Wz*sin(psi)*sin(theta)*cos(phi)

In [ ]:
simplify(trigsimp(res_quat.d))

-Wx*sin(theta) + Wy*sin(phi)*cos(theta) + Wz*cos(phi)*cos(theta)

In [ ]:
Rotation_matrix.T*Matrix([[0], [0], [Wz]])

Matrix([
[ Wz*(sin(phi)*sin(psi) + sin(theta)*cos(phi)*cos(psi))],
[Wz*(-sin(phi)*cos(psi) + sin(psi)*sin(theta)*cos(phi))],
[                                Wz*cos(phi)*cos(theta)]])

In [ ]:
import numpy as np

# Numerical values
L = 2/2
b = 1
d = 1

# Precompute useful numbers
half_L = L / 2.0
sqrt3 = np.sqrt(3)
row3_val = sqrt3 * half_L

# Construct the 4x6 matrix T
T = np.array([
    [  1,     1,      1,      1,      1,      1     ],
    [ -L,     L,   half_L, -half_L,  half_L, -half_L],
    [  0,     0, row3_val, -row3_val, row3_val, -row3_val],
    [ -d/b,  d/b,   -d/b,    d/b,   -d/b,    d/b   ]
])

print("Matrix T:")
print(T)

# Calculate the Moore–Penrose pseudoinverse of T
T_pinv = np.linalg.pinv(T)

print("\nMoore–Penrose pseudoinverse of T:")
print(T_pinv/ 0.166666666666667)


Matrix T:
[[ 1.         1.         1.         1.         1.         1.       ]
 [-1.         1.         0.5       -0.5        0.5       -0.5      ]
 [ 0.         0.         0.8660254 -0.8660254  0.8660254 -0.8660254]
 [-1.         1.        -1.         1.        -1.         1.       ]]

Moore–Penrose pseudoinverse of T:
[[ 1.         -1.8        -0.34641016 -1.2       ]
 [ 1.          1.8         0.34641016  1.2       ]
 [ 1.          0.6         0.69282032 -0.6       ]
 [ 1.         -0.6        -0.69282032  0.6       ]
 [ 1.          0.6         0.69282032 -0.6       ]
 [ 1.         -0.6        -0.69282032  0.6       ]]


In [4]:
import numpy as np

# Constants
l = 0.25
kt = 1
km = 0.1
keta = km / kt
sqrt2 = np.sqrt(2)

factor = kt * l / sqrt2
# Construct the matrix inside the big brackets
M = factor * np.array([
    [sqrt2/l,   sqrt2/l,    sqrt2/l,    sqrt2/l],
    [1,        -1,         -1,         1],
    [1,         1,         -1,        -1],
    [-sqrt2*keta, sqrt2*keta, -sqrt2*keta, sqrt2*keta]
])

print("Matrix M:")
print(M)

# Compute the pseudoinverse
M_pinv = np.linalg.pinv(M)

print("\nMoore–Penrose Pseudoinverse of M:")
print(M_pinv/0.25)

Matrix M:
[[ 1.         1.         1.         1.       ]
 [ 0.1767767 -0.1767767 -0.1767767  0.1767767]
 [ 0.1767767  0.1767767 -0.1767767 -0.1767767]
 [-0.025      0.025     -0.025      0.025    ]]

Moore–Penrose Pseudoinverse of M:
[[  1.           5.65685425   5.65685425 -40.        ]
 [  1.          -5.65685425   5.65685425  40.        ]
 [  1.          -5.65685425  -5.65685425 -40.        ]
 [  1.           5.65685425  -5.65685425  40.        ]]
